### ISSUE TITLE
Empty Sampling Rate in IPFIX in v2.0.0

### ISSUE THREAD

**Issue by mieczkowski** [netsampler/goflow2#206]
**Describe the bug**

In version 2.0.0 with no mapping config (or with provided in cmd/goflow2/mapping) `sampling_rate` in IPFIX (maybe in netflow_v9 too?) is always 0. 

With previous version (v1.3.5) it is filled with correct value.

In sflow everything is ok.

**To Reproduce**

mapping.yaml:
```yaml
formatter:
  fields:
    - type
    - time_received_ns
    - sampling_rate
    - packets
# with or without mapping for sampling_rate
ipfix:
  mapping:
    - field: 34
      destination: sampling_rate
```

```bash
./bin/goflow2 -listen "netflow://:5054?count=5" -mapping mapping.yaml
(...)
{"type":"IPFIX","time_received_ns":1692717004888748779,"sampling_rate":0,"packets":4}
{"type":"IPFIX","time_received_ns":1692717004889875193,"sampling_rate":0,"packets":1}
{"type":"IPFIX","time_received_ns":1692717004891125195,"sampling_rate":0,"packets":1}
{"type":"IPFIX","time_received_ns":1692717004892344462,"sampling_rate":0,"packets":1}
{"type":"IPFIX","time_received_ns":1692717004931292813,"sampling_rate":0,"packets":1}
{"type":"IPFIX","time_received_ns":1692717004933758147,"sampling_rate":0,"packets":1}
{"type":"IPFIX","time_received_ns":1692717004934781487,"sampling_rate":0,"packets":3}
```

After checkout to v1.3.5 and run without mapping:

```json
{"Type":"IPFIX","TimeReceived":1692717105,"SamplingRate":500,"Bytes":7500,"Packets":5 ... }
```

**Expected behavior**
sampling_rate in IPFIX should be filled

**GoFlow2:**
 - Version: 2.0.0
 - Environment: docker or `go run`
 - OS: Debian 11.7
