### ISSUE TITLE
How to add TemplateId to the collected fields

### ISSUE THREAD

**Issue by bpereto** [netsampler/goflow2#266]
in my use-case I receive different templates and would like to distinguish beteween, as they contain different fields.

I added the field "template_id" to the mapping, but this seems to be always 0.

mapping.yaml
```
formatter:
  fields:
    - type
    - template_id
    - time_flow_start_ns
    - time_flow_end_ns
 ipfix:
  mapping:
    - field: 145
      destination: template_id
```

cmd:
```
goflow2 -mapping mapping.yaml -listen=netflow://:3001
```

Output:
```
{"type":"IPFIX","template_id":0,"time_flow_start_ns":1703066706587000000,"time_flow_end_ns":1703066708986000000}
{"type":"IPFIX","template_id":0,"time_flow_start_ns":1703066705621000000,"time_flow_end_ns":1703066707813000000}
{"type":"IPFIX","template_id":0,"time_flow_start_ns":1703066712999000000,"time_flow_end_ns":1703066712999000000}
{"type":"IPFIX","template_id":0,"time_flow_start_ns":1703066708805000000,"time_flow_end_ns":1703066709609000000}
```

Whats the correct way of including the template id ?
