### ISSUE TITLE
Support for Cisco ASA/NSEL

### ISSUE THREAD

**Issue by JordanBarnartt** [netsampler/goflow2#307]
**Is your feature request related to a problem? Please describe.**
I am trying to use Akvorado (https://github.com/akvorado/akvorado/) to monitor NetFlows from our Cisco routers.  Akvorado uses GoFlow2 for flow decoding.  To monitor NAT'ing (i.e. which private IP was associated with which public IP during a flow), we utilize Cisco ASA/NSEL (https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/asa_netflow.html), which adds additional data to the flows, including the post-NAT addresses.  I've found that Akvorado does not handle ASA/NSEL flows properly (such as not knowing how many bytes were sent), and I believe it's because GoFlow2 isn't configured to handle them.

**Describe the solution you'd like**
Support for parsing ASA/NSEL flows.  Alternatively, have an extra fields mapping type for IP addresses.

**Describe alternatives you've considered**
I've tried mapping extra fields (like NF_F_XLATE_SRC_ADDR_IPV4) as described in the README, but there doesn't seem to be a way to conveniently map a field containing an IP address (the best I can do is a string where each two digits are the hex of one section of the IP).

**Comment by lspgn** [comment]
Hi @JordanBarnartt
Thank you for raising this feature request.

Is there a packet capture you could send or an excerpt of the bytes for the field/template?
This should be "custom mappable": what's your current mapping configuration?

**Comment by JordanBarnartt** [comment]
Thanks for the quick reply :)

I can't think of a way to provide a PCAP without inadvertently exposing the contents of our network traffic.  I know how to anonymize the PCAP, but not the NetFlow data itself.  I'll try my best to explain what I'm seeing.

If I run:
` ./goflow2-2.1.3-linux-x86_64 -listen 'flow://:29996' -mapping mapping.yaml`
 
with the mapping file:
```
formatter:
  fields:
    - type
    - time_received_ns
    - bytes
    - packets
    - src_addr
    - dst_addr
    - etype
    - proto
    - src_port
    - dst_port
    - src_addr_nat
  protobuf:
    - name: src_addr_nat
      index: 999
      type: string

netflowv9:
  mapping:
    - field: 225
      destination: src_addr_nat
```

I got the field number (255) from https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/asa_netflow.html, and I wasn't sure what to use as the protobuf index, so I went with 999.

I get output like (dst_addr changes for privacy):
`{"type":"NETFLOW_V9","time_received_ns":1712241597455623857,"bytes":0,"packets":0,"src_addr":"10.32.24.37","dst_addr":"1.1.1.1","etype":"IPv4","proto":"TCP","src_port":58776,"dst_port":80,"src_addr_nat":"81617c1e"}`

Looking at src_addr_nat and converting from hex to decimal:
81 -> 129
61 -> 97
7c -> 124
1e -> 30
So, the NAT'ed address is 129.97.124.30, which is correct.
