### ISSUE TITLE
IPFIX Application (372-374) to Clickhouse

### ISSUE THREAD

**Issue by PacketThrowr** [netsampler/goflow2#388]
I am trying to get IPFIX Application information into Clickhouse. Below are the changes that I have made and the errors I am seeing.

Added the lines to pb/flow.proto
```
  string application_category_name = 372;
  string application_sub_category_name = 373;
  string application_group_name = 374;

```

I ran `make proto` and can see these fields in the `flow.pb.go` file.
```
cat flow.pb.go | grep Application
        ApplicationCategoryName    string                   `protobuf:"bytes,372,opt,name=application_category_name,json=applicationCategoryName,proto3" json:"application_category_name,omitempty"`
        ApplicationSubCategoryName string                   `protobuf:"bytes,373,opt,name=application_sub_category_name,json=applicationSubCategoryName,proto3" json:"application_sub_category_name,omitempty"`
        ApplicationGroupName       string                   `protobuf:"bytes,374,opt,name=application_group_name,json=applicationGroupName,proto3" json:"application_group_name,omitempty"`
func (x *FlowMessage) GetApplicationCategoryName() string {
                return x.ApplicationCategoryName
func (x *FlowMessage) GetApplicationSubCategoryName() string {
                return x.ApplicationSubCategoryName
func (x *FlowMessage) GetApplicationGroupName() string {
                return x.ApplicationGroupName
```

Created a mapping file mapping.yaml:

```
ipfix:
  mapping:
    - field: 372
      destination: ApplicationCategoryName
    - field: 373
      destination: ApplicationSubCategoryName
    - field: 374
      destination: ApplicationGroupName
```

Added the mapping file to the docker-compose file:
```
    command:
      - -transport.kafka.brokers=kafka:9092
      - -transport=kafka
      - -transport.kafka.topic=flows
      - -format=bin
      - -mapping=/conf/mapping.yaml
    volumes:
      - ./mapping.yaml:/conf/mapping.yaml
```
Updated the clickhouse `flow.proto` file:
```
  string application_category_name = 372;
  string application_sub_category_name = 373;
  string application_group_name = 374;

```

I updated the create.sh file to create the 3 additional fields.
```
docker-compose exec db clickhouse-client --query="DESCRIBE TABLE flows"
time_received_ns        UInt64
time_flow_start_ns      UInt64
sequence_num    UInt32
sampling_rate   UInt64
sampler_address FixedString(16)
src_addr        FixedString(16)
dst_addr        FixedString(16)
src_as  UInt32
dst_as  UInt32
etype   UInt32
proto   UInt32
src_port        UInt32
dst_port        UInt32
bytes   UInt64
packets UInt64
application_category_name       String
application_sub_category_name   String
application_group_name  String

docker-compose exec db clickhouse-client --query="DESCRIBE TABLE flows_raw"
date    Date
time_inserted_ns        DateTime64(9)
time_received_ns        DateTime64(9)
time_flow_start_ns      DateTime64(9)
sequence_num    UInt32
sampling_rate   UInt64
sampler_address FixedString(16)
src_addr        FixedString(16)
dst_addr        FixedString(16)
src_as  UInt32
dst_as  UInt32
etype   UInt32
proto   UInt32
src_port        UInt32
dst_port        UInt32
bytes   UInt64
packets UInt64
application_category_name       String
application_sub_category_name   String
application_group_name  String
```

I then built the containers:`docker-compose up -d --build`

When I look at the rows in flows_raw, there is no data for the 3 new application fields. Last 2 rows:
```
2025-04-08      2025-04-08 19:54:28.000000000   2025-04-08 19:54:26.097425664   2025-04-08 19:54:14.705999872   85494      0       \n\0e▒\0\0\0\0\0\0\0\0\0\0\0\0  \n▒▒2\0\0\0\0\0\0\0\0\0\0\0\0   ▒▒▒\0\0\0\0\0\0\0\0\0\0\0\0     0 02048    6       60259   443     2091    8
2025-04-08      2025-04-08 19:54:28.000000000   2025-04-08 19:54:26.097425664   2025-04-08 19:54:14.753999872   85494      0       \n\0e▒\0\0\0\0\0\0\0\0\0\0\0\0  ▒▒▒\0\0\0\0\0\0\0\0\0\0\0\0     \n▒▒2\0\0\0\0\0\0\0\0\0\0\0\0   0 02048    6       443     60259   13644   13
```

The GoFlow2 container logs are filled with
```
kcg-goflow2-1  | time=2025-04-08T19:23:47.448Z level=WARN msg="template error" scheme=netflow hostname="" port=2055 count=1 workers=2 blocking=false queue_size=1000000
kcg-goflow2-1  | time=2025-04-08T19:23:48.449Z level=WARN msg="template error" scheme=netflow hostname="" port=2055 count=1 workers=2 blocking=false queue_size=1000000
```

When I take a pcap, I see that there are packets that just include the normal source/destination IP, port, etc. and then another packet is received with just the application information. This is my lack of understanding with IPFIX, but since this traffic comes in on different packets, is there a way to link this information together? I am not sure if I a missing a step or misunderstanding how IPFIX and GoFlow2 will interact with this information.

The source is a Cisco IOS-XE Router on 17.12.4

**Comment by PacketThowr** [comment]
Also, sorry I didn't mean to open this as a bug and instead as a question. I am unable to update the label on this from what I can find

**Comment by PacketThowr** [comment]
Here is a pcap that shows the packets containing the IP information, the other packets containing the Application information, and the IPFIX templates.

[capture.zip](https://github.com/user-attachments/files/19656269/capture.zip)

**Comment by PacketThowr** [comment]
I stopped receiving the template error messages:
kcg-goflow2-1  | time=2025-04-08T19:23:48.449Z level=WARN msg="template error" scheme=netflow hostname="" port=2055 count=1 workers=2 blocking=false queue_size=1000000


It just looks like my issue now is mapping these Application fields to Clickhouse. I also am trying to get tcp_flags into clickhouse as well with no luck. I also made a few changes to the mapping file based on some examples I found posted in other issues.

New mapping file:
```
formatter:
  protobuf:
    - name: application_category_name
      index: 372
      type: varint
    - name: application_sub_category_name
      index: 373
      type: varint
    - name: application_group_name
      index: 374
      type: varint
    - name: tcp_flags
      index: 6
      type: varint
ipfix:
  mapping:
    - field: 372
      destination: application_category_name
    - field: 373
      destination: application_sub_category_name
    - field: 374
      destination: application_group_name
    - field: 26
      destination: tcp_flags
```

The tcp_flags already exists in the compose/kcg/clickhouse/flow.proto
```
  uint32 tcp_flags = 26;
```

I updated the flows and flows_raw table in clickhouse for tcp_flags as well.
```
[opc@phx-pv-flow01 clickhouse]$ docker compose exec db clickhouse-client --query="DESCRIBE TABLE flows_raw"
WARN[0000] /data/goflow2/compose/kcg/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
date    Date
time_inserted_ns        DateTime64(9)
time_received_ns        DateTime64(9)
time_flow_start_ns      DateTime64(9)
sequence_num    UInt32
sampling_rate   UInt64
sampler_address FixedString(16)
src_addr        FixedString(16)
dst_addr        FixedString(16)
src_as  UInt32
dst_as  UInt32
etype   UInt32
proto   UInt32
src_port        UInt32
dst_port        UInt32
bytes   UInt64
packets UInt64
src_ip_str      String
dst_ip_str      String
application_category_name       String
application_sub_category_name   String
application_group_name  String
tcp_flags       UInt32
[opc@phx-pv-flow01 clickhouse]$ docker compose exec db clickhouse-client --query="DESCRIBE TABLE flows"
WARN[0000] /data/goflow2/compose/kcg/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
time_received_ns        UInt64
time_flow_start_ns      UInt64
sequence_num    UInt32
sampling_rate   UInt64
sampler_address FixedString(16)
src_addr        FixedString(16)
dst_addr        FixedString(16)
src_as  UInt32
dst_as  UInt32
etype   UInt32
proto   UInt32
src_port        UInt32
dst_port        UInt32
bytes   UInt64
packets UInt64
tcp_flags       UInt32
application_category_name       String
application_sub_category_name   String
application_group_name  String
```

**Comment by lspgn** [comment]
Hi @PacketThowr,
You don't need to generate the Go code as you have the custom mapping.

Could you run GoFlow2 with `goflow2 -config mapping.yaml` with the following config

```yaml
formatter:
  fields:
    - type
    - time_received_ns
    - sequence_num
    - application_category_name
  protobuf:
    - name: application_category_name
      index: 372
      type: string
  render:
    application_category_name: none # if ascii text, you can do string instead of none
ipfix:
  mapping:
    - field: 12441
      destination: application_category_name
      penprovided: true
      pen: 9
```

It's an [enterprise field](https://github.com/netsampler/goflow2/blob/d06ecaf4d64f14e8c88a5d437787e3a90f7f9dd5/docs/protocols.md?plain=1#L209-L212) that needs to get mapped to a protobuf with a certain ID.
Then ClickHouse needs to have access to the updated `flow.proto`

Getting something like with your pcap:

```
$ go run cmd/goflow2/main.go -mapping cmd/goflow2/mapping4.yaml
time=2025-04-13T15:37:39.775-07:00 level=INFO msg="starting GoFlow2"
time=2025-04-13T15:37:39.775-07:00 level=INFO msg="starting collection" scheme=sflow hostname="" port=6343 count=1 workers=2 blocking=false queue_size=1000000
time=2025-04-13T15:37:39.776-07:00 level=INFO msg="starting collection" scheme=netflow hostname="" port=2055 count=1 workers=2 blocking=false queue_size=1000000
{"type":"IPFIX","time_received_ns":1744583862500728000,"sequence_num":65233,"application_category_name":"e166b4800004dec1"}
{"type":"IPFIX","time_received_ns":1744583862500728000,"sequence_num":65233,"application_category_name":"e0fff1f0001102ff"}
{"type":"IPFIX","time_received_ns":1744583862500756000,"sequence_num":65236,"application_category_name":"e149b2c0000fe34c"}
```
